services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MeineKrankenkasse\Typo3SearchAlgolia\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    # Commands
    MeineKrankenkasse\Typo3SearchAlgolia\Command\IndexQueueWorkerCommand:
        tags:
            -   name: 'console.command'
                command: 'mkk:queue:index:worker'
                description: 'A worker indexing the items in the index queue.'
                schedulable: true

    # DataHandlerHook
    MeineKrankenkasse\Typo3SearchAlgolia\Hook\DataHandlerHook:
        public: true

    # Indexers
    MeineKrankenkasse\Typo3SearchAlgolia\Service\Indexer\PageIndexer:
        public: true

    MeineKrankenkasse\Typo3SearchAlgolia\Service\Indexer\ContentIndexer:
        public: true

    MeineKrankenkasse\Typo3SearchAlgolia\Service\Indexer\NewsIndexer:
        public: true

    # Event listeners
    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\UpdateAssembledPageDocumentEventListener:
        tags:
            -   name: event.listener
                event: MeineKrankenkasse\Typo3SearchAlgolia\Event\AfterDocumentAssembledEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\RecordUpdateEventListener:
        tags:
            -   name: event.listener
                event: MeineKrankenkasse\Typo3SearchAlgolia\Event\DataHandlerRecordUpdateEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\RecordDeleteEventListener:
        tags:
            -   name: event.listener
                event: MeineKrankenkasse\Typo3SearchAlgolia\Event\DataHandlerRecordDeleteEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\CreateDefaultDocumentIdEventListener:
        tags:
            -   name: event.listener
                event: MeineKrankenkasse\Typo3SearchAlgolia\Event\CreateUniqueDocumentIdEvent
