services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MeineKrankenkasse\Typo3SearchAlgolia\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    MeineKrankenkasse\Typo3SearchAlgolia\Controller\EnqueueOneController:
        public: true

    MeineKrankenkasse\Typo3SearchAlgolia\Service\TypoScriptService:
        public: true

    # Commands
    MeineKrankenkasse\Typo3SearchAlgolia\Command\IndexQueueWorkerCommand:
        tags:
            -   name: 'console.command'
                command: 'mkk:queue:index:worker'
                description: 'A worker indexing the items in the index queue.'
                schedulable: true

    # DataHandlerHook
    MeineKrankenkasse\Typo3SearchAlgolia\Hook\DataHandlerHook:
        public: true

#    # Indexers
#    MeineKrankenkasse\Typo3SearchAlgolia\Service\Indexer\PageIndexer:
#        public: true
#
#    MeineKrankenkasse\Typo3SearchAlgolia\Service\Indexer\ContentIndexer:
#        public: true
#
#    MeineKrankenkasse\Typo3SearchAlgolia\Service\Indexer\NewsIndexer:
#        public: true

    # Event listeners
    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\CreateDefaultDocumentIdEventListener:
        tags:
            -   name: event.listener
                event: MeineKrankenkasse\Typo3SearchAlgolia\Event\CreateUniqueDocumentIdEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\UpdateAssembledContentElementDocumentEventListener:
        tags:
            -   name: event.listener
                event: MeineKrankenkasse\Typo3SearchAlgolia\Event\AfterDocumentAssembledEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\UpdateAssembledFileDocumentEventListener:
        tags:
            -   name: event.listener
                event: MeineKrankenkasse\Typo3SearchAlgolia\Event\AfterDocumentAssembledEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\UpdateAssembledPageDocumentEventListener:
        tags:
            -   name: event.listener
                event: MeineKrankenkasse\Typo3SearchAlgolia\Event\AfterDocumentAssembledEvent

    # Record event listeners
    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\Record\RecordUpdateEventListener:
        tags:
            -   name: event.listener
                event: MeineKrankenkasse\Typo3SearchAlgolia\Event\DataHandlerRecordUpdateEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\Record\RecordMoveEventListener:
        tags:
            -   name: event.listener
                event: MeineKrankenkasse\Typo3SearchAlgolia\Event\DataHandlerRecordMoveEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\Record\RecordDeleteEventListener:
        tags:
            -   name: event.listener
                event: MeineKrankenkasse\Typo3SearchAlgolia\Event\DataHandlerRecordDeleteEvent

    # Resource event listeners
    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\Resource\AfterFileAddedEventListener:
        tags:
            -   name: event.listener
                event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\Resource\AfterFileDeletedEventListener:
        tags:
            -   name: event.listener
                event: TYPO3\CMS\Core\Resource\Event\AfterFileDeletedEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\Resource\AfterFileCopiedEventListener:
        tags:
            -   name: event.listener
                event: TYPO3\CMS\Core\Resource\Event\AfterFileCopiedEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\Resource\AfterFileMovedEventListener:
        tags:
            -   name: event.listener
                event: TYPO3\CMS\Core\Resource\Event\AfterFileMovedEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\Resource\AfterFileRenamedEventListener:
        tags:
            -   name: event.listener
                event: TYPO3\CMS\Core\Resource\Event\AfterFileRenamedEvent

    MeineKrankenkasse\Typo3SearchAlgolia\EventListener\Resource\AfterFileReplacedEventListener:
        tags:
            -   name: event.listener
                event: TYPO3\CMS\Core\Resource\Event\AfterFileReplacedEvent
